name: Build and Push Docker image to ECR

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    name: Build and Push Docker image to ECR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: nginx
          IMAGE_TAG: ${{ github.sha }}
          
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 041952152622.dkr.ecr.us-east-1.amazonaws.com
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "${ECR_REGISTRY}"

      - name: Copy Docker Compose file to EC2
        env:
          KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          DOCKER_IMAGE: ${{ ECR_REGISTRY }}/nginx:${{ github.sha }}
        run: |
          echo "$KEY" > private_key && chmod 600 private_key
          scp -o StrictHostKeyChecking=no -i private_key docker-compose.yml ubuntu@3.94.205.160:/home/ubuntu/
          echo "${DOCKER_IMAGE}"
          ssh -o StrictHostKeyChecking=no -i private_key ubuntu@3.94.205.160 '
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 041952152622.dkr.ecr.us-east-1.amazonaws.com
          sed -i "s|image: nginx:.*|image: $DOCKER_IMAGE|" /home/ubuntu/docker-compose.yml
          docker compose down
          docker compose up -d
          '
         # sed -i "s|image: .*|image: $DOCKER_IMAGE|" /home/ubuntu/docker-compose.yml
          
         # ssh -o StrictHostKeyChecking=no -i private_key ubuntu@52.71.255.212 '
        #    sed -i "s|image: .*|image: $DOCKER_IMAGE|" /home/ubuntu/docker-compose.yml
         #   docker-compose down
          #  docker-compose up -d
          #'

        #  ls /home/runner/work/nginx-app/nginx-app
          # ssh -o StrictHostKeyChecking=no -i ${{secrets.EC2_SSH_PRIVATE_KEY}} ubuntu@52.71.255.212
          # ls
        # scp -o StrictHostKeyChecking=no -i ${{ secrets.EC2_SSH_PRIVATE_KEY }} docker-compose.yml ubuntu@52.71.255.212:/home/ubuntu/  
        #  echo "$EC2_SSH_PRIVATE_KEY" > private_key && chmod 400 private_key
        # ssh -o StrictHostKeyChecking=no -i ${{EC2_SSH_PRIVATE_KEY}} ubuntu@52.71.255.212  

        # curl -LJO https://raw.githubusercontent.com/sureshkumarc46/nginx-app/main/docker-compose.yml

         
